Repository ProdEng-JavaFrenzy/restaurant, pull requests merged in 2022-03, with the labels that each got.

#1 Add initial project files
  .dockerignore
  .editorconfig
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .vscode/extensions.json
  Dockerfile
  Dockerfile.build
  Dockerfile.multistage
  Makefile
  build.gradle
  build.sh
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/javafrenzy/restaurant/RestaurantApplication.java
  src/main/java/com/javafrenzy/restaurant/controller/HelloController.java
  src/main/java/com/javafrenzy/restaurant/data/MongoConfig.java
  src/main/resources/application.properties
  src/test/java/com/javafrenzy/restaurant/RestaurantApplicationTests.java
Labels: enhancement

#2 basic functionality
  .dockerignore
  Makefile
  src/main/java/com/javafrenzy/restaurant/RestaurantApplication.java
  src/main/java/com/javafrenzy/restaurant/config/MongoConfig.java
  src/main/java/com/javafrenzy/restaurant/controller/HelloController.java
  src/main/java/com/javafrenzy/restaurant/controller/ReservationController.java
  src/main/java/com/javafrenzy/restaurant/exception/ReservationNotFoundException.java
  src/main/java/com/javafrenzy/restaurant/model/Reservation.java
  src/main/java/com/javafrenzy/restaurant/model/ReservationNotFoundAdvice.java
  src/main/java/com/javafrenzy/restaurant/repository/ReservationRepository.java
  src/main/java/com/javafrenzy/restaurant/service/ReservationService.java
  src/main/java/com/javafrenzy/restaurant/utils/GenerateIdentifier.java
  src/test/java/com/javafrenzy/restaurant/RestaurantApplicationTests.java
Labels: documentation, enhancement

#3 Remove squash/rebase requirement in PR template checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#9 Feature / Add unit tests for table service, dto and controller
  src/main/java/com/javafrenzy/restaurant/dto/TableRequestDto.java
  src/main/java/com/javafrenzy/restaurant/model/Reservation.java
  src/main/java/com/javafrenzy/restaurant/service/ReservationService.java
  src/test/java/com/javafrenzy/restaurant/RestaurantApplicationTests.java
  src/test/java/com/javafrenzy/restaurant/controller/TableControllerTest.java
  src/test/java/com/javafrenzy/restaurant/dto/TableRequestDtoTest.java
  src/test/java/com/javafrenzy/restaurant/service/TableServiceTest.java
Labels: enhancement

#7 Unit testing so far
  build.gradle
  src/test/java/com/javafrenzy/restaurant/model/ReservationTest.java
  src/test/java/com/javafrenzy/restaurant/model/TableTest.java
  src/test/java/com/javafrenzy/restaurant/utils/GenerateIdentifierTest.java
Labels: enhancement

#8 reservations tests
  src/main/java/com/javafrenzy/restaurant/model/Reservation.java
  src/main/java/com/javafrenzy/restaurant/service/ReservationService.java
  src/test/java/com/javafrenzy/restaurant/controller/ReservationControllerTest.java
  src/test/java/com/javafrenzy/restaurant/service/ReservationServiceTest.java
Labels: enhancement

#12 Feature / Add integration tests for table service and repository
  src/test/java/com/javafrenzy/restaurant/service/ReservationServiceTest.java
  src/test/java/com/javafrenzy/restaurant/service/TableServiceIntegrationTest.java
Labels: enhancement

#10 Unit tests changes & performance tests
  performance_tests/DELETE delete table from reservation.jmx
  performance_tests/DELETE delete table.jmx
  performance_tests/DELETE deleteReservation.jmx
  performance_tests/GET Reservations.jmx
  performance_tests/GET checkReservation.jmx
  performance_tests/GET tables.jmx
  performance_tests/POST add table to reservation .jmx
  performance_tests/POST add table.jmx
  performance_tests/POST addReservation.jmx
  performance_tests/PUT update table.jmx
  performance_tests/PUT updateReservation.jmx
  src/test/java/com/javafrenzy/restaurant/model/ReservationTest.java
  src/test/java/com/javafrenzy/restaurant/model/TableTest.java
  src/test/java/com/javafrenzy/restaurant/utils/GenerateIdentifierTest.java
Labels: enhancement

#11 integration testing/ reservations
  src/test/java/com/javafrenzy/restaurant/service/ReservationServiceIT.java
  src/test/java/com/javafrenzy/restaurant/service/ReservationServiceITMock.java
Labels: enhancement
